apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/cri-dockerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-12-02T12:27:29Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
    minikube.k8s.io/commit: 210b148df93a80eb872ecbeb7e35281b3c582c61
    minikube.k8s.io/name: minikube
    minikube.k8s.io/primary: "true"
    minikube.k8s.io/updated_at: 2024_12_02T20_27_32_0700
    minikube.k8s.io/version: v1.34.0
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: minikube
  resourceVersion: "1041"
  uid: 54a8e808-0d27-43ae-851f-b8e649d7459e
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
status:
  addresses:
  - address: 192.168.49.2
    type: InternalIP
  - address: minikube
    type: Hostname
  allocatable:
    cpu: "32"
    ephemeral-storage: 960107552Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 65018704Ki
    nvidia.com/gpu: "1"
    pods: "110"
  capacity:
    cpu: "32"
    ephemeral-storage: 960107552Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 65018704Ki
    nvidia.com/gpu: "1"
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2024-12-02T12:39:14Z"
    lastTransitionTime: "2024-12-02T12:27:28Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2024-12-02T12:39:14Z"
    lastTransitionTime: "2024-12-02T12:27:28Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2024-12-02T12:39:14Z"
    lastTransitionTime: "2024-12-02T12:27:28Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2024-12-02T12:39:14Z"
    lastTransitionTime: "2024-12-02T12:27:29Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - ollama/ollama@sha256:55977eb618082df0f81ea197a75dc1710e54524f2ef71fa1a8b83cc0148b6e2f
    - ollama/ollama:latest
    sizeBytes: 4648236690
  - names:
    - nvcr.io/nvidia/k8s-device-plugin@sha256:ed39e22c8b71343fb996737741a99da88ce6c75dd83b5c520e0b3d8e8a884c47
    sizeBytes: 351206338
  - names:
    - kubernetesui/dashboard@sha256:2e500d29e9d5f4a086b908eb8dfe7ecac57d2ab09d65b24f588b1d449841ef93
    sizeBytes: 245710051
  - names:
    - registry.k8s.io/etcd@sha256:a6dc63e6e8cfa0307d7851762fa6b629afb18f28d8aa3fab5a6e91b4af60026a
    - registry.k8s.io/etcd:3.5.15-0
    sizeBytes: 147945345
  - names:
    - registry.k8s.io/kube-apiserver@sha256:470179274deb9dc3a81df55cfc24823ce153147d4ebf2ed649a4f271f51eaddf
    - registry.k8s.io/kube-apiserver:v1.31.0
    sizeBytes: 94175876
  - names:
    - registry.k8s.io/kube-proxy@sha256:c727efb1c6f15a68060bf7f207f5c7a765355b7e3340c513e582ec819c5cd2fe
    - registry.k8s.io/kube-proxy:v1.31.0
    sizeBytes: 91471299
  - names:
    - registry.k8s.io/kube-controller-manager@sha256:f6f3c33dda209e8434b83dacf5244c03b59b0018d93325ff21296a142b68497d
    - registry.k8s.io/kube-controller-manager:v1.31.0
    sizeBytes: 88380387
  - names:
    - registry.k8s.io/kube-scheduler@sha256:96ddae9c9b2e79342e0551e2d2ec422c0c02629a74d928924aaa069706619808
    - registry.k8s.io/kube-scheduler:v1.31.0
    sizeBytes: 67363811
  - names:
    - registry.k8s.io/coredns/coredns@sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1
    - registry.k8s.io/coredns/coredns:v1.11.1
    sizeBytes: 59820619
  - names:
    - kubernetesui/metrics-scraper@sha256:76049887f07a0476dc93efc2d3569b9529bf982b22d29f356092ce206e98765c
    sizeBytes: 43815949
  - names:
    - gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944
    - gcr.io/k8s-minikube/storage-provisioner:v5
    sizeBytes: 31465472
  - names:
    - registry.k8s.io/pause@sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a
    - registry.k8s.io/pause:3.10
    sizeBytes: 735760
  nodeInfo:
    architecture: amd64
    bootID: c828df1b-2858-4dca-b3fc-c269459bb415
    containerRuntimeVersion: docker://27.2.0
    kernelVersion: 6.8.0-40-generic
    kubeProxyVersion: ""
    kubeletVersion: v1.31.0
    machineID: a13a6f859fed431bab2edb6d5ea12665
    operatingSystem: linux
    osImage: Ubuntu 22.04.4 LTS
    systemUUID: d4554f26-9168-475b-b89a-95fdacac576d
