apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          resources:
            limits:
              cpu: "12"
              memory: "24Gi"
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent  # 僅在鏡像不存在時拉取
          lifecycle:
            postStart:
              exec:
                command: ["ollama", "pull", "codestral"]
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
